#customhost = "employee.cvizqxos8p8v.us-east-1.rds.amazonaws.com" 
customhost = "mydbinstance.caefqqugke36.us-east-1.rds.amazonaws.com" 
customuser = "aws_user"
custompass = "iamhugosoh76541"
customdb = "mydbinstance"
custombucket = "sohbennie-employee"
customregion = "us-east-1"
